/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/mail/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send email */
        post: operations["Mail_sendMail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/crm/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login employee (CRM) */
        post: operations["EmployeeAuth_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/crm/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh access token (CRM) */
        post: operations["EmployeeAuth_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/crm/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout employee (CRM) */
        post: operations["EmployeeAuth_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/crm/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current employee (CRM) */
        get: operations["EmployeeAuth_getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/crm/auth/employee/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register new Employee (CRM) */
        post: operations["EmployeeRegistration_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lk/auth/member/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check if user exists (for Member registration) */
        post: operations["MembersAuth_checkUserExists"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lk/auth/member/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register new Member (Site) */
        post: operations["MembersAuth_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lk/auth/member/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Queue member documents/signature upload (Site) */
        post: operations["MembersAuth_uploadFiles"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lk/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login Member (Site) */
        post: operations["MemberAuth_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lk/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh access token (Site) */
        post: operations["MemberAuth_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lk/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout Member (Site) */
        post: operations["MemberAuth_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lk/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current Member (Site) */
        get: operations["MemberAuth_getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/crm/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List members for CRM preview (without authentication) */
        get: operations["CrmMembers_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/crm/members/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get member details for CRM preview (without authentication) */
        get: operations["CrmMembers_byId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update member details from CRM (temporary no-auth) */
        patch: operations["CrmMembers_update"];
        trace?: never;
    };
    "/crm/members/{id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Re-upload member files from CRM (temporary no-auth) */
        patch: operations["CrmMembers_updateFiles"];
        trace?: never;
    };
    "/crm/members/{id}/identity-documents/{documentId}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Preview identity document image */
        get: operations["CrmMembers_identityDocumentPreview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/crm/members/{id}/signature/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Preview signature image */
        get: operations["CrmMembers_signaturePreview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["App_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SendEmailRequestDto: {
            /**
             * @description Email
             * @example test@example.com
             */
            email: string;
            /**
             * @description Subject
             * @example Welcome to the realm of NestJS
             */
            subject: string;
            /**
             * @description Template
             * @example text
             */
            body: string;
            /**
             * @description Name
             * @example John
             */
            name: string;
            /**
             * @description Surname
             * @example Doe
             */
            surname: string;
        };
        EmployeeLoginDto: {
            /** @example employee@example.com */
            email: string;
            /** @example password123 */
            password: string;
        };
        EmployeeAuthResponseDto: {
            /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
            accessToken: string;
            /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
            refreshToken: string;
            /**
             * @example {
             *       "id": "123e4567-e89b-12d3-a456-426614174000",
             *       "email": "employee@example.com",
             *       "name": "John Employee",
             *       "role": "manager"
             *     }
             */
            employee: Record<string, never>;
        };
        ApiErrorResponseDto: {
            /**
             * @description Error message
             * @example Validation failed
             */
            message: string;
            /**
             * @description Array of validation errors (for validation errors)
             * @example [
             *       "email must be an email",
             *       "password must be longer than 8 characters"
             *     ]
             */
            errors?: string[];
        };
        RefreshTokenDto: {
            /**
             * @description Refresh token
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            refreshToken: string;
        };
        EmployeeRefreshTokenResponseDto: {
            /**
             * @description New access token
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            accessToken: string;
            /**
             * @description New refresh token
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            refreshToken: string;
        };
        EmployeeLogoutResponseDto: {
            /**
             * @description Logout message
             * @example Logged out successfully
             */
            message: string;
        };
        EmployeeMeResponseDto: {
            /** @example 123e4567-e89b-12d3-a456-426614174000 */
            id: string;
            /** @example employee@example.com */
            email: string;
            /** @example John Employee */
            name: string;
            /** @example +1234567890 */
            phone?: string;
            /** @example manager */
            role: string;
            /** @example Senior Manager */
            position?: string;
            /** @example Sales */
            department?: string;
            /** @example true */
            isActive: boolean;
            /**
             * Format: date-time
             * @example 2024-01-01T00:00:00.000Z
             */
            lastLoginAt?: string;
            /**
             * Format: date-time
             * @example 2024-01-01T00:00:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2024-01-01T00:00:00.000Z
             */
            updatedAt: string;
        };
        RegisterEmployeeDto: {
            /** @example employee@example.com */
            email: string;
            /**
             * @description Password must contain uppercase, lowercase and number
             * @example Password123
             */
            password: string;
            /** @example John */
            name: string;
            /** @example Doe */
            surname?: string;
            /** @example +1234567890 */
            phone?: string;
            /**
             * @example manager
             * @enum {string}
             */
            role?: "employee" | "manager" | "admin";
            /** @example Senior Manager */
            position?: string;
            /** @example Sales */
            department?: string;
        };
        CheckUserExistsDto: {
            /** @example user@example.com */
            email: string;
        };
        CheckUserExistsResponseDto: {
            /** @example true */
            exists: boolean;
            /** @example true */
            hasEmployee?: boolean;
            /** @example true */
            hasMember?: boolean;
            /** @example User already registered as Employee. Do you want to register as Member? */
            message?: string;
        };
        RegisterMemberDto: {
            /** @example user@example.com */
            email: string;
            /**
             * @description Password must contain uppercase, lowercase and number
             * @example Password123
             */
            password: string;
            /** @example John */
            name: string;
            /** @example Doe */
            surname?: string;
            /** @example +1234567890 */
            phone?: string;
            /** @example 2005-11-16 */
            birthday?: string;
            /** @example ID */
            documentType?: string;
            /** @example 592-9185990 */
            documentNumber?: string;
            /** @example 123 Main St */
            address?: string;
            /** @example true */
            isMedical?: boolean;
            /** @example true */
            isMj?: boolean;
            /** @example true */
            isRecreation?: boolean;
        };
        RegisterMemberResponseDto: {
            /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
            accessToken: string;
            /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
            refreshToken: string;
            /**
             * @description Created member identifier
             * @example 123e4567-e89b-12d3-a456-426614174999
             */
            memberId: string;
            /**
             * @example {
             *       "id": "123e4567-e89b-12d3-a456-426614174000",
             *       "email": "user@example.com",
             *       "name": "John",
             *       "surname": "Doe"
             *     }
             */
            user: Record<string, never>;
            /**
             * @example {
             *       "message": "User already exists as Employee. Do you want to register as Member?",
             *       "hasEmployee": true
             *     }
             */
            warning?: Record<string, never>;
        };
        UploadMemberFilesDto: {
            /**
             * @description Document type. Required when any identity document side is provided.
             * @example passport
             */
            documentType?: string;
            /**
             * @description Identity document first side as data URL (base64).
             * @example data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAA...
             */
            documentFirst?: string;
            /**
             * @description Identity document second side as data URL (base64).
             * @example data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAA...
             */
            documentSecond?: string;
            /**
             * @description Signature image as data URL (base64).
             * @example data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAA...
             */
            signature?: string;
        };
        UploadMemberFilesResponseDto: {
            /** @example true */
            queued: boolean;
            /** @example 214 */
            jobId: string;
        };
        LoginDto: {
            /** @example user@example.com */
            email: string;
            /** @example Password123 */
            password: string;
        };
        AuthResponseDto: {
            /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
            accessToken: string;
            /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
            refreshToken: string;
            /**
             * @example {
             *       "id": "507f1f77bcf86cd799439011",
             *       "email": "user@example.com"
             *     }
             */
            user: Record<string, never>;
        };
        RefreshTokenResponseDto: {
            /**
             * @description New access token
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            accessToken: string;
            /**
             * @description New refresh token
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            refreshToken: string;
        };
        LogoutDto: {
            /**
             * @description Logout message
             * @example Logged out successfully
             */
            message: string;
        };
        UserMeResponseDto: {
            /** @example 507f1f77bcf86cd799439011 */
            id: string;
            /** @example user@example.com */
            email: string;
            /** @example John Doe */
            name: string;
            /** @example +1234567890 */
            phone?: string;
            /** @example true */
            isActive: boolean;
            /**
             * Format: date-time
             * @example 2024-01-01T00:00:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2024-01-01T00:00:00.000Z
             */
            updatedAt: string;
        };
        CrmMemberDto: {
            /** @example 123e4567-e89b-12d3-a456-426614174000 */
            id: string;
            /** @example 123e4567-e89b-12d3-a456-426614174000 */
            userId: string;
            /** @example user@example.com */
            email: string;
            /** @example John */
            name: string;
            /** @example Doe */
            surname: string | null;
            /** @example +1234567890 */
            phone: string | null;
            /** @example active */
            status: string;
            /** @example true */
            isActive: boolean;
            /** @example true */
            emailConfirmed: boolean;
            /** @example 2024-01-01T00:00:00.000Z */
            createdAt: string;
        };
        CrmMemberIdentityDocumentDto: {
            /** @example 123e4567-e89b-12d3-a456-426614174000 */
            id: string;
            /** @example passport */
            type: string;
            /** @example front */
            side: string | null;
            /** @example https://example.com/storage/path.jpg */
            storagePath: string;
            /** @example 2024-01-01T00:00:00.000Z */
            createdAt: string;
        };
        CrmMemberSignatureDto: {
            /** @example 123e4567-e89b-12d3-a456-426614174000 */
            id: string;
            /** @example https://example.com/storage/path.jpg */
            storagePath: string;
            /** @example 2024-01-01T00:00:00.000Z */
            createdAt: string;
        };
        CrmMemberMjStatusDto: {
            /** @example 123e4567-e89b-12d3-a456-426614174000 */
            id: string;
            /** @example code */
            code: string;
            /** @example name */
            name: string;
        };
        CrmMemberDocumentDto: {
            /** @example 123e4567-e89b-12d3-a456-426614174000 */
            id: string;
            /** @example passport */
            type: string;
            /** @example name */
            name: string;
            /** @example 1234567890 */
            number: string | null;
            /** @example 2024-01-01T00:00:00.000Z */
            createdAt: string;
        };
        CrmMemberFullDto: {
            /** @example 123e4567-e89b-12d3-a456-426614174000 */
            id: string;
            /** @example 123e4567-e89b-12d3-a456-426614174000 */
            userId: string;
            /** @example user@example.com */
            email: string;
            /** @example John */
            name: string;
            /** @example Doe */
            surname: string | null;
            /** @example +1234567890 */
            phone: string | null;
            /** @example active */
            status: string;
            /** @example true */
            isActive: boolean;
            /** @example true */
            emailConfirmed: boolean;
            /** @example 2024-01-01T00:00:00.000Z */
            createdAt: string;
            /** @example 2024-01-01T00:00:00.000Z */
            updatedAt: string;
            /**
             * @example [
             *       null
             *     ]
             */
            identityDocuments: components["schemas"]["CrmMemberIdentityDocumentDto"][];
            signature: components["schemas"]["CrmMemberSignatureDto"] | null;
            /**
             * @example [
             *       null
             *     ]
             */
            mjStatuses: components["schemas"]["CrmMemberMjStatusDto"][];
            /**
             * @example [
             *       null
             *     ]
             */
            documents: components["schemas"]["CrmMemberDocumentDto"][];
            /** @example 2024-01-01T00:00:00.000Z */
            birthday: string | null;
            /** @example 123 Main St */
            address: string | null;
            /** @example 1234567890 */
            membershipNumber: string | null;
            /** @example Notes */
            notes: string | null;
        };
        CrmMemberUpdateDto: {
            /** @example 123e4567-e89b-12d3-a456-426614174000 */
            id?: string;
            /** @example 123e4567-e89b-12d3-a456-426614174000 */
            userId?: string;
            /** @example user@example.com */
            email?: string;
            /** @example John */
            name?: string;
            /** @example Doe */
            surname?: string | null;
            /** @example +1234567890 */
            phone?: string | null;
            /** @example active */
            status?: string;
            /** @example true */
            isActive?: boolean;
            /** @example true */
            emailConfirmed?: boolean;
            /** @example 2024-01-01T00:00:00.000Z */
            createdAt?: string;
            /** @example 2024-01-01T00:00:00.000Z */
            updatedAt?: string;
            /**
             * @example [
             *       null
             *     ]
             */
            identityDocuments?: components["schemas"]["CrmMemberIdentityDocumentDto"][];
            signature?: components["schemas"]["CrmMemberSignatureDto"] | null;
            /**
             * @example [
             *       null
             *     ]
             */
            mjStatuses?: components["schemas"]["CrmMemberMjStatusDto"][];
            /**
             * @example [
             *       null
             *     ]
             */
            documents?: components["schemas"]["CrmMemberDocumentDto"][];
            /** @example John */
            birthday?: string | null;
            /** @example 123 Main St */
            address?: string | null;
            /** @example 1234567890 */
            membershipNumber?: string | null;
            /** @example Notes */
            notes?: string | null;
            /** @example true */
            isMedical: boolean;
            /** @example true */
            isMj: boolean;
            /** @example true */
            isRecreation: boolean;
            /** @example passport */
            documentType: string | null;
            /** @example 1234567890 */
            documentNumber: string | null;
        };
        CrmMemberFilesRequestDto: {
            /**
             * @description Document type. Required when any identity document side is provided.
             * @example passport
             */
            documentType?: string;
            /**
             * @description Identity document first side as data URL (base64).
             * @example data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAA...
             */
            documentFirst?: string;
            /**
             * @description Identity document second side as data URL (base64).
             * @example data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAA...
             */
            documentSecond?: string;
            /**
             * @description Signature image as data URL (base64).
             * @example data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAA...
             */
            signature?: string;
        };
        StreamableFile: Record<string, never>;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type SchemaSendEmailRequestDto = components['schemas']['SendEmailRequestDto'];
export type SchemaEmployeeLoginDto = components['schemas']['EmployeeLoginDto'];
export type SchemaEmployeeAuthResponseDto = components['schemas']['EmployeeAuthResponseDto'];
export type SchemaApiErrorResponseDto = components['schemas']['ApiErrorResponseDto'];
export type SchemaRefreshTokenDto = components['schemas']['RefreshTokenDto'];
export type SchemaEmployeeRefreshTokenResponseDto = components['schemas']['EmployeeRefreshTokenResponseDto'];
export type SchemaEmployeeLogoutResponseDto = components['schemas']['EmployeeLogoutResponseDto'];
export type SchemaEmployeeMeResponseDto = components['schemas']['EmployeeMeResponseDto'];
export type SchemaRegisterEmployeeDto = components['schemas']['RegisterEmployeeDto'];
export type SchemaCheckUserExistsDto = components['schemas']['CheckUserExistsDto'];
export type SchemaCheckUserExistsResponseDto = components['schemas']['CheckUserExistsResponseDto'];
export type SchemaRegisterMemberDto = components['schemas']['RegisterMemberDto'];
export type SchemaRegisterMemberResponseDto = components['schemas']['RegisterMemberResponseDto'];
export type SchemaUploadMemberFilesDto = components['schemas']['UploadMemberFilesDto'];
export type SchemaUploadMemberFilesResponseDto = components['schemas']['UploadMemberFilesResponseDto'];
export type SchemaLoginDto = components['schemas']['LoginDto'];
export type SchemaAuthResponseDto = components['schemas']['AuthResponseDto'];
export type SchemaRefreshTokenResponseDto = components['schemas']['RefreshTokenResponseDto'];
export type SchemaLogoutDto = components['schemas']['LogoutDto'];
export type SchemaUserMeResponseDto = components['schemas']['UserMeResponseDto'];
export type SchemaCrmMemberDto = components['schemas']['CrmMemberDto'];
export type SchemaCrmMemberIdentityDocumentDto = components['schemas']['CrmMemberIdentityDocumentDto'];
export type SchemaCrmMemberSignatureDto = components['schemas']['CrmMemberSignatureDto'];
export type SchemaCrmMemberMjStatusDto = components['schemas']['CrmMemberMjStatusDto'];
export type SchemaCrmMemberDocumentDto = components['schemas']['CrmMemberDocumentDto'];
export type SchemaCrmMemberFullDto = components['schemas']['CrmMemberFullDto'];
export type SchemaCrmMemberUpdateDto = components['schemas']['CrmMemberUpdateDto'];
export type SchemaCrmMemberFilesRequestDto = components['schemas']['CrmMemberFilesRequestDto'];
export type SchemaStreamableFile = components['schemas']['StreamableFile'];
export type $defs = Record<string, never>;
export interface operations {
    Mail_sendMail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendEmailRequestDto"];
            };
        };
        responses: {
            /** @description Email sent */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": boolean;
                };
            };
        };
    };
    EmployeeAuth_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmployeeLoginDto"];
            };
        };
        responses: {
            /** @description Employee logged in successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeAuthResponseDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    EmployeeAuth_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenDto"];
            };
        };
        responses: {
            /** @description Token refreshed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeRefreshTokenResponseDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    EmployeeAuth_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeLogoutResponseDto"];
                };
            };
        };
    };
    EmployeeAuth_getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current employee information */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeMeResponseDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    EmployeeRegistration_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterEmployeeDto"];
            };
        };
        responses: {
            /** @description Employee registered successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeAuthResponseDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    MembersAuth_checkUserExists: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckUserExistsDto"];
            };
        };
        responses: {
            /** @description User existence check result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckUserExistsResponseDto"];
                };
            };
        };
    };
    MembersAuth_register: {
        parameters: {
            query: {
                force: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterMemberDto"];
            };
        };
        responses: {
            /** @description Member registered successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterMemberResponseDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    MembersAuth_uploadFiles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadMemberFilesDto"];
            };
        };
        responses: {
            /** @description Member files were queued for asynchronous processing */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadMemberFilesResponseDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    MemberAuth_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            /** @description Member logged in successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    MemberAuth_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenDto"];
            };
        };
        responses: {
            /** @description Token refreshed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshTokenResponseDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    MemberAuth_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutDto"];
                };
            };
        };
    };
    MemberAuth_getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current Member information */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserMeResponseDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    CrmMembers_list: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of members */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrmMemberDto"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    CrmMembers_byId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Member details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrmMemberFullDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    CrmMembers_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrmMemberUpdateDto"];
            };
        };
        responses: {
            /** @description Member details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrmMemberFullDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    CrmMembers_updateFiles: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrmMemberFilesRequestDto"];
            };
        };
        responses: {
            /** @description Member details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrmMemberFullDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    CrmMembers_identityDocumentPreview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                documentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Identity document image */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamableFile"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    CrmMembers_signaturePreview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signature image */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamableFile"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    App_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
